version: "3"
services:
  app:
    image: qrxt37/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "0.0.0.0:8080:8080"
    working_dir: /app
    command: make test
