version: "3"
services:
  app:
    depends_on:
      db:
        condition: service_healthy
    image: qrxt37/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "0.0.0.0:8080:8080"
    working_dir: /app
    command: make test
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    depends_on:
      - app
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
