name: ci

on:
  push:
    branches:
      - 'main'

env:
  TAG: ${{ secrets.DOCKERHUB_USERNAME }}/devops-for-programmers-project-74:test
  DATABASE_HOST: db
  DATABASE_NAME: postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: password

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          load: true
          context: .
          tags: ${{ env.TAG }}
      -
        name: Run tests
        run: make test
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ env.TAG }}
